# Generated by Django 5.2.7 on 2025-10-23 22:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_suporte', models.IntegerField(unique=True, verbose_name='Código Suporte')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Username')),
                ('tipo_usuario', models.CharField(choices=[('suporte', 'Suporte'), ('colaborador', 'Colaborador')], default='colaborador', max_length=15, verbose_name='Tipo de Usuário')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
        ),
    ]
