# Generated by Django 4.2 on 2025-10-29 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0003_departamento_chamado_confirmacaoresolucao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interacaochamado',
            name='lida',
            field=models.BooleanField(default=False, verbose_name='Notificação lida'),
        ),
        migrations.AddField(
            model_name='interacaochamado',
            name='usuario_notificado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_project.usuario', verbose_name='Usuário notificado'),
        ),
        migrations.AlterField(
            model_name='interacaochamado',
            name='acao_bot',
            field=models.CharField(blank=True, choices=[('saudacao', 'Saudação Inicial'), ('confirmacao', 'Confirmação do Chamado'), ('classificacao', 'Classificação da Urgência'), ('status', 'Atualização de Status'), ('resposta', 'Resposta Automática'), ('verificacao_tempo', 'Verificação de Tempo'), ('verificacao_urgente', 'Verificação Urgente'), ('finalizacao', 'Finalização'), ('notificacao_novo_chamado', 'Notificação Novo Chamado')], max_length=50, null=True, verbose_name='Ação do Bot'),
        ),
    ]
