# Generated by Django 4.2 on 2025-10-29 20:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0004_interacaochamado_lida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id_notificacao', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(choices=[('novo_chamado', 'Novo Chamado'), ('atualizacao', 'Atualização'), ('mensagem', 'Nova Mensagem')], default='novo_chamado', max_length=20)),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='app_project.chamado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='app_project.usuario')),
            ],
            options={
                'db_table': 'notificacoes',
                'ordering': ['-criado_em'],
            },
        ),
    ]
