# Generated by Django 4.2 on 2025-10-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0005_notificacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interacaochamado',
            options={'ordering': ['criado_em']},
        ),
        migrations.RemoveField(
            model_name='interacaochamado',
            name='lida',
        ),
        migrations.RemoveField(
            model_name='interacaochamado',
            name='usuario_notificado',
        ),
        migrations.AlterField(
            model_name='interacaochamado',
            name='acao_bot',
            field=models.CharField(blank=True, choices=[('saudacao', 'Saudação Inicial'), ('confirmacao', 'Confirmação do Chamado'), ('classificacao', 'Classificação da Urgência'), ('status', 'Atualização de Status'), ('resposta', 'Resposta Automática'), ('verificacao_tempo', 'Verificação de Tempo'), ('verificacao_urgente', 'Verificação Urgente'), ('finalizacao', 'Finalização'), ('notificacao_novo_chamado', 'Notificação Novo Chamado'), ('atualizacao_status', 'Atualização de Status'), ('mensagem', 'Mensagem'), ('inicio', 'Início')], max_length=50, null=True, verbose_name='Ação do Bot'),
        ),
    ]
