# Generated by Django 4.2 on 2025-11-05 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0006_alter_interacaochamado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='controle_chat_suporte',
            field=models.BooleanField(default=False, verbose_name='Controle do Chat pelo Suporte'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='suporte_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_atendidos', to='app_project.usuario', verbose_name='Suporte Responsável'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='visualizado_suporte',
            field=models.BooleanField(default=False, verbose_name='Visualizado pelo Suporte'),
        ),
        migrations.AddField(
            model_name='interacaochamado',
            name='suporte_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_project.usuario', verbose_name='Suporte Responsável'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='nome_solicitante',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome do Solicitante'),
        ),
    ]
