# Generated by Django 4.2 on 2025-11-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0007_chamado_controle_chat_suporte_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chamado',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AlterModelOptions(
            name='interacaochamado',
            options={'ordering': ['criado_em'], 'verbose_name': 'Interação do Chamado', 'verbose_name_plural': 'Interações dos Chamados'},
        ),
        migrations.AlterModelOptions(
            name='notificacao',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Notificação', 'verbose_name_plural': 'Notificações'},
        ),
        migrations.AddField(
            model_name='interacaochamado',
            name='visualizada_automatica',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('em_andamento', 'Em Andamento'), ('resolvido', 'Resolvido')], default='em_andamento', max_length=15, verbose_name='Status do Chamado'),
        ),
        migrations.AlterField(
            model_name='interacaochamado',
            name='acao_bot',
            field=models.CharField(blank=True, choices=[('saudacao', 'Saudação Inicial'), ('confirmacao', 'Confirmação do Chamado'), ('classificacao', 'Classificação da Urgência'), ('status', 'Atualização de Status'), ('resposta', 'Resposta Automática'), ('verificacao_tempo', 'Verificação de Tempo'), ('verificacao_urgente', 'Verificação Urgente'), ('finalizacao', 'Finalização'), ('notificacao_novo_chamado', 'Notificação Novo Chamado'), ('atualizacao_status', 'Atualização de Status'), ('mensagem', 'Mensagem'), ('inicio', 'Início'), ('intermediacao_ativa', 'Intermediação Ativa'), ('mensagem_fallback', 'Mensagem Fallback')], max_length=50, null=True, verbose_name='Ação do Bot'),
        ),
    ]
