# Generated by Django 4.2 on 2026-02-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0008_alter_chamado_options_alter_interacaochamado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='broadcast',
            field=models.BooleanField(default=False, verbose_name='Notificação Broadcast'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='broadcast_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID do Broadcast'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('novo_chamado', 'Novo Chamado'), ('atualizacao', 'Atualização'), ('mensagem', 'Nova Mensagem'), ('novo_chamado_broadcast', 'Novo Chamado (Broadcast)'), ('sistema_novo_chamado', 'Sistema - Novo Chamado')], default='novo_chamado', max_length=30),
        ),
    ]
