# Generated by Django 5.2.6 on 2025-10-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='codigo_suporte',
            field=models.IntegerField(verbose_name='Código Suporte'),
        ),
    ]
