# Generated by Django 5.2.6 on 2025-10-24 18:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0002_alter_usuario_codigo_suporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Departamento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id_chamado', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Problema')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('nome_solicitante', models.CharField(max_length=100, verbose_name='Nome do Solicitante')),
                ('modalidade_presencial', models.BooleanField(default=True, verbose_name='Modalidade Presencial')),
                ('urgencia', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Nível de Urgência')),
                ('status', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('resolvido', 'Resolvido'), ('cancelado', 'Cancelado')], default='em_andamento', max_length=15, verbose_name='Status do Chamado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data_resolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução')),
                ('id_legivel', models.CharField(blank=True, max_length=20, unique=True, verbose_name='ID Legível')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_project.usuario', verbose_name='Usuário Solicitante')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_project.departamento', verbose_name='Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmacaoResolucao',
            fields=[
                ('id_confirmacao', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_confirmacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Confirmação')),
                ('satisfacao', models.IntegerField(choices=[(1, '1 - Muito Insatisfeito'), (2, '2'), (3, '3'), (4, '4'), (5, '5 - Muito Satisfeito')], verbose_name='Nível de Satisfação')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentário')),
                ('chamado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacao', to='app_project.chamado')),
                ('confirmado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_project.usuario', verbose_name='Confirmado por')),
            ],
        ),
        migrations.CreateModel(
            name='InteracaoChamado',
            fields=[
                ('id_interacao', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remetente', models.CharField(choices=[('usuario', 'Usuário'), ('bot', 'Bot'), ('suporte', 'Suporte')], max_length=10, verbose_name='Remetente')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('acao_bot', models.CharField(blank=True, choices=[('saudacao', 'Saudação Inicial'), ('confirmacao', 'Confirmação do Chamado'), ('classificacao', 'Classificação da Urgência'), ('status', 'Atualização de Status'), ('resposta', 'Resposta Automática')], max_length=50, null=True, verbose_name='Ação do Bot')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='app_project.chamado')),
            ],
        ),
    ]
